# -*- coding: utf-8 -*-
"""monte_carlo_portfolio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYbR6NpUvPEVYWSxqshGW6DoG4PYS21M
"""

# -*- coding: utf-8 -*-
"""Monte Carlo Portfolio Simulation (Cholesky Decomposition)"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy import stats
import yfinance as yf

# 1. DATA EXTRACTION
print("Fetching data from Yahoo Finance...")
tickers_map = {"AAPL": "aapl_us", "KO": "coke_us", "TSLA": "tsla_us", "GC=F": "xauusd"}
raw_data = yf.download(list(tickers_map.keys()), start="2020-01-01", end="2024-01-01")['Close']
assets = raw_data.rename(columns=tickers_map).dropna()

print("\n--- Data Sample ---")
print(assets.head())

# Plotting Tesla for a quick check
plt.figure(figsize=(10, 4))
plt.plot(assets['tsla_us'], color='red')
plt.title("Tesla Historical Price")
plt.show()

# 2. RETURNS AND CORRELATION
returns = assets.copy()
for asset in ['aapl_us', 'coke_us', 'tsla_us', 'xauusd']:
    returns[asset] = returns[asset].pct_change()
returns = returns.dropna()

corr = returns.corr()
print("\n--- Historical Correlation Matrix ---")
print(corr)

# 3. MONTE CARLO SIMULATION (Cholesky Decomposition)
cholesky_decomp = np.linalg.cholesky(corr)
randoms = np.random.randn(4, returns.shape[0])
volatility = returns.agg("std")

# MatMul keeps the historical correlation intact in our random data
simulated = pd.DataFrame(np.matmul(cholesky_decomp, randoms), index=['aapl_us', 'coke_us', 'tsla_us', 'xauusd']).T
simulated = simulated * volatility

print("\n--- Simulated Correlation Matrix (Checking Cholesky effectiveness) ---")
print(simulated.corr())

# 4. PORTFOLIO CALCULATION
weights = [0.2, 0.2, 0.3, 0.3]

# Simulated Portfolio
sim_portfolio = pd.DataFrame((weights * simulated).sum(axis=1))
sim_portfolio.columns = ["ret"]
sim_portfolio["value"] = (1 + sim_portfolio.ret).cumprod() * 100

# Actual Historical Portfolio
portfolio = pd.DataFrame((weights * returns).sum(axis=1))
portfolio.columns = ["ret"]
portfolio["value"] = (1 + portfolio.ret).cumprod() * 100

# 5. VISUALIZATION (Distributions)
fig, axs = plt.subplots(nrows=2, figsize=(12, 8), constrained_layout=True, sharex=True)
num_bins = 40

# Simulated distribution
axs[0].hist(sim_portfolio.ret, bins=num_bins, density=True, label="Portfolio returns")
axs[0].set_title("Distribution of returns of the simulated portfolio")
mu, std = stats.norm.fit(sim_portfolio.ret)
xmin, xmax = sim_portfolio.ret.min(), sim_portfolio.ret.max()
x = np.linspace(xmin, xmax, 100)
p = stats.norm.pdf(x, mu, std)
axs[0].plot(x, p, 'k', linewidth=2, label="Normal distribution", c="orange", linestyle="dashed")
axs[0].legend()

# Actual distribution
axs[1].hist(portfolio.ret, bins=num_bins, density=True, label="Portfolio returns")
axs[1].set_title("Distribution of returns of the actual portfolio")
mu, std = stats.norm.fit(portfolio.ret)
xmin, xmax = portfolio.ret.min(), portfolio.ret.max()
x = np.linspace(xmin, xmax, 100)
p = stats.norm.pdf(x, mu, std)
axs[1].plot(x, p, 'k', linewidth=2, label="Normal distribution", c="orange", linestyle="dashed")
axs[1].legend()

# Save the plot for GitHub
plt.savefig("monte_carlo_distribution.png", dpi=120)
plt.show()